# pages/reports.py
# The REPORTS page lets users download their data and analysis results.
# Three download options: CSV, plain text report, Excel spreadsheet.

import os, sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import streamlit as st
import pandas as pd
import io  # io lets us create file-like objects in memory (without saving to disk)

from core.data_cleaner  import get_quality_report
from utils.helpers      import (
    stop_if_no_data,
    get_filename,
    get_number_columns,
    get_text_columns,
    get_completeness,
)

# Stop the page if no data is loaded
stop_if_no_data()

df       = st.session_state["df"]
filename = get_filename()
num_cols = get_number_columns(df)
txt_cols = get_text_columns(df)
score    = get_completeness(df)
report   = get_quality_report(df)

# ── Page header ───────────────────────────────────────────────────────────────
st.title("📄 Reports & Downloads")
st.write("Download your dataset or a full analysis report.")
st.markdown("---")

# Show which file is loaded
st.success(f"📂 Current dataset: **{filename}** — {df.shape[0]:,} rows × {df.shape[1]} columns")

# ── Download buttons ──────────────────────────────────────────────────────────
st.subheader("⬇️ Download Options")
st.write("Choose a format to download:")

btn1, btn2, btn3 = st.columns(3)

# ── Build the text report first (used by both btn2 and the preview section) ──
# We build this BEFORE the buttons so it's always available on the page

missing_section = ""
if len(report["missing_per_column"]) == 0:
    missing_section = "  None found — data is complete!"
else:
    for col, count in report["missing_per_column"].items():
        pct = round(count / len(df) * 100, 1)
        missing_section += f"\n  • {col}: {count} missing ({pct}%)"

# Build top correlations section
correlation_section = ""
if len(num_cols) >= 2:
    corr_matrix = df[num_cols].corr()
    pairs = []
    for i in range(len(num_cols)):
        for j in range(i + 1, len(num_cols)):
            pairs.append((
                abs(corr_matrix.iloc[i, j]),
                num_cols[i],
                num_cols[j],
                round(corr_matrix.iloc[i, j], 3)
            ))
    pairs.sort(reverse=True)  # sort strongest correlation first
    for _, col_a, col_b, value in pairs[:5]:  # top 5 only
        correlation_section += f"\n  • {col_a} & {col_b}: {value}"
else:
    correlation_section = "\n  Not enough numeric columns"

# Assemble the full report text
report_lines = [
    "=" * 55,
    "         INSIGHTGEN AI — ANALYSIS REPORT",
    "=" * 55,
    "",
    f"File         : {filename}",
    f"Rows         : {df.shape[0]:,}",
    f"Columns      : {df.shape[1]}",
    f"Numeric cols : {len(num_cols)}",
    f"Text cols    : {len(txt_cols)}",
    f"Completeness : {score}%",
    f"Duplicates   : {report['duplicate_count']}",
    "",
    "── COLUMN LIST ──────────────────────────────────",
]
for col in df.columns:
    report_lines.append(f"  • {col}  ({df[col].dtype})")

report_lines += [
    "",
    "── MISSING VALUES ───────────────────────────────",
    missing_section,
    "",
    "── STATISTICS ───────────────────────────────────",
    df.describe().round(2).to_string(),
    "",
    "── TOP CORRELATIONS ─────────────────────────────",
    correlation_section,
    "",
    "=" * 55,
    "           Generated by InsightGen AI",
    "=" * 55,
]
report_text = "\n".join(report_lines)

# ── Download buttons ──────────────────────────────────────────────────────────

# Button 1 — Download as CSV
with btn1:
    # Convert DataFrame to CSV text, then encode as bytes
    csv_data = df.to_csv(index=False).encode("utf-8")

    # st.download_button creates a button that downloads a file when clicked
    st.download_button(
        label="📥 Download CSV",
        data=csv_data,
        file_name=f"{filename.split('.')[0]}_cleaned.csv",  # e.g. "sales_cleaned.csv"
        mime="text/csv",  # tells the browser what kind of file this is
        use_container_width=True,
    )
    st.caption("Clean version of your dataset")

# Button 2 — Download Text Report
with btn2:
    st.download_button(
        label="📥 Download TXT Report",
        data=report_text.encode("utf-8"),
        file_name=f"{filename.split('.')[0]}_report.txt",
        mime="text/plain",
        use_container_width=True,
    )
    st.caption("Full analysis as plain text")

# Button 3 — Download Excel Report
with btn3:
    # io.BytesIO() creates an in-memory file (like a file buffer)
    # We write the Excel file into this buffer instead of saving to disk
    excel_buffer = io.BytesIO()

    # pd.ExcelWriter writes multiple sheets into one Excel file
    with pd.ExcelWriter(excel_buffer, engine="openpyxl") as writer:
        # Sheet 1: Statistics
        df.describe().round(2).to_excel(writer, sheet_name="Statistics")

        # Sheet 2: First 50 rows of data
        df.head(50).to_excel(writer, sheet_name="Sample Data", index=False)

        # Sheet 3: Missing value counts
        missing_df = df.isnull().sum().reset_index()
        missing_df.columns = ["Column", "Missing Count"]
        missing_df["Missing %"] = (missing_df["Missing Count"] / len(df) * 100).round(1)
        missing_df.to_excel(writer, sheet_name="Missing Values", index=False)

        # Sheet 4: Column info
        schema_df = pd.DataFrame({
            "Column": df.columns,
            "Data Type": df.dtypes.astype(str).values,
            "Unique Values": [df[c].nunique() for c in df.columns],
        })
        schema_df.to_excel(writer, sheet_name="Column Info", index=False)

    # Rewind the buffer to the beginning so it can be read for download
    excel_buffer.seek(0)

    st.download_button(
        label="📥 Download Excel Report",
        data=excel_buffer,
        file_name=f"{filename.split('.')[0]}_report.xlsx",
        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        use_container_width=True,
    )
    st.caption("Multi-sheet Excel with stats and data")

# ── Report Preview ────────────────────────────────────────────────────────────
st.markdown("---")
st.subheader("👀 Report Preview")
st.write("This is what the TXT report looks like:")

# st.text_area shows a scrollable text box
st.text_area(
    label="Report content:",
    value=report_text,
    height=400,
)

# ── Statistics Table ──────────────────────────────────────────────────────────
if num_cols:
    st.markdown("---")
    st.subheader("📊 Full Statistics Table")
    st.write(
        "This shows count, mean, min, max, and percentiles "
        "for all numeric columns:"
    )
    st.dataframe(df.describe().round(2), use_container_width=True)